[package]
version = "1.0.0"
name = "epdtest"
authors.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5.23"
librustic = { path = "../librustic" }
